'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LocalizationContext = createContext();

// Extended Translation dictionaries
const translations = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    welcome: 'Welcome to our site',
    login: 'Login',
    signup: 'Sign Up',
    search: 'Search...',
    heroTitle: 'Your <span class="text-green-600">success</span> journey start with us!',
    heroDescription: 'we enable companies to thrive in a rapidly evolving digital landscape<br />Ready to transform? Let\'s explore how we can elevate your organisation together.',
    applyOnline: 'Apply online',
    discover: 'Discover',
    ellipseAlt: 'Ellipse',
    vectorAlt: 'vector',
    planeAlt: 'plane',
    locationAlt: 'location',
    studentAlt: 'Student',
      heroTitlePart1: 'Your',
    heroTitleHighlight: 'success',
    heroTitlePart2: 'journey start with us!',
    heroDescriptionLine1: 'we enable companies to thrive in a rapidly evolving digital landscape',
    heroDescriptionLine2: 'Ready to transform? Let\'s explore how we can elevate your organisation together.',
    // Feature Section Localization
     digitalTransformation: 'Digital Transformation',
    digitalTransformationDesc: 'Modernize your processes, streamline operations, and embrace technology that drives efficiency and long-term business growth.',
    boutiqueRecruitment: 'Boutique Recruitment',
    boutiqueRecruitmentDesc: 'Find the right talent through tailored recruitment services designed to build agile, high-performing teams for your organization.',
    endToEndSupport: 'End-to-End Support',
    endToEndSupportDesc: 'From strategy to execution, we provide comprehensive guidance and continuous support to ensure smooth adoption and sustainable results.',
    learnMore: 'Learn More',
    graduationAlt: 'graduation cap',
      // Feedback section translations
    quickIntro: 'Quick Intro',
    quickIntroTitle: 'Here\'s a quick intro about us',
    introVideoTitle: 'Company Introduction Video',
    videoNotSupported: 'Your browser does not support the video tag.',
     // Partners section translations
    ourPartners: 'Our Partners',
    partnersDescription: 'We have quality partners in a variety of destinations around the globe.',
    bacAlt: 'BAC',
    cloudCredentialAlt: 'Cloud Credential Council',
    dinersClubAlt: 'Diners Club',
    discoverAlt: 'Discover',
    lssiAlt: 'LSSI',
    amaAlt: 'American Marketing Association',
    pdtsAlt: 'PDTS',
    mountainAlt: 'mountain',
     // Certifications section translations
    ourSpecializations: 'OUR SPECIALIZATIONS',
    popularCertifications: 'Certifications',
    internationalCertifications: 'International Certifications',
    executivePrograms: 'Executive Programs',
    // International Certifications
    microsoftAzure: 'Microsoft Azure',
    devops: 'DevOps',
    networkEngineering: 'Network Engineering',
    windowsServer: 'Windows Server',
    dataEngineering: 'Data Engineering',
    microsoftDynamics: 'Microsoft Dynamics',
    microsoft365: 'Microsoft 365',
    microsoftTeams: 'Microsoft Teams',
    msPowerPlatform: 'MS Power Platform',
    cyberSecurity: 'Cyber Security',
    management: 'Management',
    leanSixSigma: 'Lean Six Sigma Institute',
    agileCertifications: 'Agile Certifications',
    scrumCertification: 'Scrum Certification',
    // Executive Programs
    python: 'Python',
    sql: 'SQL',
    javascript: 'JavaScript',
    html: 'HTML',
    css: 'CSS',
    java: 'Java',
    r: 'R',
    excel: 'Excel',
    php: 'PHP',
    swift: 'Swift',
    c: 'C',
    powerBI: 'Power BI',
    reactNative: 'React Native',
    nodejs: 'Nodejs',
      // Steps section translations
    stepsTitle: 'STEPS',
    stepsSubtitle: 'Steps to get yourself certified',
    stepsDescription: 'Follow this simple 5-step process to achieve your certification and unlock new career opportunities',
    exploreCertifications: 'Explore Certifications',
    exploreCertificationsDesc: 'Browse through our wide range of certification programs and find the perfect fit for your career goals.',
    enrollYourself: 'Enroll yourself',
    enrollYourselfDesc: 'Choose your program and complete the simple enrollment process to get started immediately.',
    attendClasses: 'Attend Classes',
    attendClassesDesc: 'Participate in interactive online or in-person classes with expert instructors.',
    completeTasks: 'Complete Tasks',
    completeTasksDesc: 'Finish assignments, practical exercises, and projects to demonstrate your skills.',
    getCertified: 'Certified',
    getCertifiedDesc: 'Receive your industry-recognized certification and take your career to the next level.',
     // FAQ section translations
    faqTitle: 'FAQ',
    faqSubtitle: 'Frequently asked question',
    faqDescriptionLine1: 'Still do you have any questions to know?',
    faqDescriptionLine2: 'Feel free to ask our experts here.',
    askYourQuestions: 'ASK YOUR QUESTIONS',
    // FAQ Questions and Answers
    faqQuestion1: 'How is get admission in abroad university?',
    faqAnswer1: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
    faqQuestion2: 'Do you offer complete solution for students?',
    faqAnswer2: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
    faqQuestion3: 'Which country is safe and better for higher study?',
    faqAnswer3: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
    faqQuestion4: 'Which country offer PR after study getting job?',
    faqAnswer4: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
    faqQuestion5: 'Can I get scholarship with my low cGPA?',
    faqAnswer5: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
    faqQuestion6: 'Do you allow accommodation for students in abroad?',
    faqAnswer6: 'Norway, USA, UK, Germany & Italy is most safest country in the world for Bangladeshi students for higher study.',
     // Footer translations
    newsletterTitle: 'Subscribe to Our Newsletter',
    newsletterDescription: 'Stay updated with our latest offers, study abroad opportunities, and educational insights',
    emailPlaceholder: 'Enter your email address',
    subscribe: 'Subscribe',
    companyLogoAlt: 'Tara Solutions Logo',
    bellIconAlt: 'Bell Icon',
    aboutSectionTitle: 'About Tara Solutions',
    aboutDescription: 'We are specialized in the corporate training and industrial leading courses',
    educationAwardAlt: 'Education Award',
    isoCertifiedAlt: 'ISO Certified',
    corporateSectionTitle: 'Corporate',
    termsConditions: 'Terms and Conditions',
    disclaimerCopyright: 'Disclaimer & Copyright',
    cookiePolicy: 'Cookie Policy',
    privacyPolicy: 'Privacy Policy',
    quickLinksTitle: 'Quick Links',
    aboutUs: 'About Us',
    getInTouchTitle: 'Get In Touch',
    locationAlt: 'Location',
    companyAddress: 'Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7',
    followUs: 'Follow Us',
    copyrightText: '© 2025 Tara Solutions. All rights reserved | Developed by',
    companyName: 'Tara Solutions',
    // About page translations
    aboutHeroBadge: 'Leading Education Consultancy',
    aboutHeroTitle: 'Shaping Futures Through Global Education',
    aboutHeroDescription1: 'Eduplan is a premier international education consultancy firm dedicated to guiding students towards their academic dreams in top-ranked universities worldwide.',
    aboutHeroDescription2: 'With our headquarters in India, we specialize in securing admissions for students to prestigious institutions across the United Kingdom, USA, Australia, Canada, Germany, Sweden, and our partner universities in Malaysia, Cyprus, and China.',
    lifetimeAccess: 'Lifetime Access',
    lifetimeAccessDesc: 'One-time payment for unlimited course access. Simple & effective!',
    lifetimeAccessAlt: 'Lifetime Access',
    expertTutors: 'Expert Tutors',
    expertTutorsDesc: 'Learn from industry experts with extensive teaching experience',
    expertTutorsAlt: 'Expert Tutors',
    practicalCurriculum: 'Practical Curriculum',
    practicalCurriculumDesc: 'World-class courses with hands-on projects that build confidence',
    practicalLearningAlt: 'Practical Learning',
    getFreeConsultation: 'Get Free Consultation',
    exploreCourses: 'Explore Courses',
    modernCampusAlt: 'Modern Campus',
    successRateAlt: 'Success Rate',
    successRate: 'Success Rate',
    studentsGuided: 'Students Guided',
    expertConsultants: 'Expert Consultants',
    coursesOffered: 'Courses Offered',
    ourCommitment: 'Our Commitment',
    missionVisionTitle: 'Building Bridges to Global Education',
    missionVisionStats: '87% of students who choose Eduplan report significant career advancement and personal growth.',
    ourVision: 'Our Vision',
    ourVisionDesc: 'To be the world\'s leading student consultancy, transforming lives through accessible global education opportunities.',
    ourMission: 'Our Mission',
    ourMissionDesc: 'Achieve excellence through innovative services that make world-class education accessible within every student\'s capacity.',
    ourGoal: 'Our Goal',
    ourGoalDesc: 'Create international study opportunities that enhance individual growth and contribute to national development.',
    successStories: 'SUCCESS STORIES',
    testimonialsTitle: 'Students Who Soared Globally',
    testimonialsDescription: 'Hear from our students who have transformed their lives through international education',
    testimonial1: 'Eduplan helped me secure admission to my dream university in the UK. The guidance was exceptional from start to finish!',
    testimonial2: 'The consultants at Eduplan are truly experts. They made the complex visa process feel simple and straightforward.',
    testimonial3: 'Thanks to Eduplan, I\'m now studying at a top Canadian university. Their support made all the difference in my journey.',
    testimonial4: 'The scholarship guidance I received was invaluable. Eduplan helped me secure funding I didn\'t even know was available.',
    ctaTitle: 'Ready to Start Your Global Education Journey?',
    ctaDescription: 'Join thousands of successful students who have transformed their lives with Eduplan\'s expert guidance.',
    startFreeConsultation: 'Start Free Consultation',
    browseCourses: 'Browse Courses',
      // Course listing translations
    courseListingTitle: 'We have {count} courses total',
    courseListingDescription: 'We have professional alliance\'s with leading Universities and Colleges around the world.',
    category: 'Category',
    certifier: 'Certifier',
    duration: 'Duration',
    modality: 'Modality',
    select: 'Select',
    filter: 'Filter',
    reset: 'Reset',
    bookMySeat: 'Book My Seat',
    courseDefaultDescription: 'Course designed for professionals seeking certification.',
    bookYourSeat: 'Book Your Seat',
    course: 'Course',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    email: 'Email',
    phone: 'Phone',
    phonePlaceholder: '+92 XXX XXXXXXX',
    message: 'Message',
    messagePlaceholder: 'Any special requirements or questions...',
    sendInquiry: 'Send Inquiry',
    inquirySentSuccess: 'Inquiry Sent Successfully!',
    thankYouMessage: 'Thank you for your interest. We\'ll get back to you soon.',
    prev: 'PREV',
    next: 'NEXT',
      // Courses page translations
    exclusivePrograms: 'Exclusive Programs',
    executivePrograms: 'Executive Programs',
    executiveProgramsDescription: 'Advanced leadership programs designed for senior professionals seeking transformative growth and strategic impact.',
    allCourses: 'All Courses',
    findPerfectCourse: 'Find the perfect course to advance your skills',
    searchCourses: 'Search courses...',
    category: 'Category',
    allCategories: 'All Categories',
    technology: 'Technology',
    allTechnologies: 'All Technologies',
    applyFilters: 'Apply Filters',
    resetAll: 'Reset All',
    coursesCount: 'Courses',
    available: 'Available',
    noCoursesFound: 'No courses found',
    adjustSearchCriteria: 'Try adjusting your search criteria or filters',
    resetFilters: 'Reset Filters',
    bookMySeat: 'Book My Seat',
    bookYourSeat: 'Book Your Seat',
    course: 'Course',
    courseDetails: 'Course Details',
    description: 'Description',
    careerOpportunities: 'Career Opportunities',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    email: 'Email',
    phone: 'Phone',
    phonePlaceholder: '+92 XXX XXXXXXX',
    message: 'Message',
    messagePlaceholder: 'Any special requirements or questions...',
    sending: 'Sending...',
    sendInquiry: 'Send Inquiry',
    inquirySentSuccess: 'Inquiry Sent Successfully!',
    thankYouMessage: 'Thank you for your interest. We\'ll get back to you soon.',
    close: 'Close',
    previous: 'Previous',
    next: 'Next',
      // Contact page translations
    contactHeroTitle: "Let's Connect",
    contactHeroDescription: "Ready to start your journey? We're here to help you every step of the way. Get in touch with our dedicated team today.",
    responseTime: "We typically respond within 2 hours",
    getInTouch: "Get in Touch",
    getInTouchDescription: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    ourOffice: "Our Office",
    officeAddress: "Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7",
    phoneNumbers: "Phone Numbers",
    phoneDetails: "+506 8701-6253 & +507 6473-6099",
    emailAddress: "Email Address",
    emailDetails: "info@tarasolutions-cr.com & gerencia@tarasolutions-cr.com",
    businessHours: "Business Hours",
    businessHoursDetails: "Mon - Fri: 9:00 AM - 6:00 PM Sat: 10:00 AM - 4:00 PM",
    followUs: "Follow Us",
    supportAvailable: "24/7",
    support: "Support Available",
    avgResponseTime: "2h",
    responseTimeLabel: "Avg. Response Time",
    sendMessage: "Send us a Message",
    sendMessageDescription: "Fill out the form below and we'll get back to you shortly.",
    personalInformation: "Personal Information",
    fullName: "Full name",
    phoneNumber: "Phone number",
    subject: "Subject",
    yourMessage: "Your Message",
    messagePlaceholder: "Tell us about your inquiry...",
    sendMessageButton: "Send Message",
    visitOurCampus: "Visit Our Campus",
    campusDescription: "Located in the heart of the city, our campus is easily accessible and equipped with state-of-the-art facilities.",
      // Terms and Conditions translations
    termsAndConditions: "Terms and Conditions",
    termsDescription: "Please read these terms carefully before using our services",
    lastUpdated: "Last Updated",
    dataProtection: "Data Protection",
    dataProtectionDesc: "Your personal information is secured with enterprise-grade encryption",
    userRights: "User Rights",
    userRightsDesc: "Clear guidelines on your rights and responsibilities",
    transparentTerms: "Transparent Terms",
    transparentTermsDesc: "No hidden clauses or complicated legal jargon",
    termsOfService: "Terms of Service",
    termsContentNotAvailable: "Terms and conditions content is not available at the moment.",
    acceptanceTitle: "Ready to Get Started?",
    acceptanceDescription: "By continuing to use our services, you acknowledge that you have read and agree to our Terms and Conditions.",
    acceptTerms: "I Accept Terms",
    downloadPDF: "Download PDF Version",
      // Privacy Policy translations
    privacyPolicy: "Privacy Policy",
    privacyDescription: "Learn how we protect and manage your personal information",
    dataSecurity: "Data Security",
    dataSecurityDesc: "Enterprise-grade encryption and security protocols",
    yourControl: "Your Control",
    yourControlDesc: "Full control over your personal data and preferences",
    transparency: "Transparency",
    transparencyDesc: "Clear information about data collection and usage",
    privacyPolicyDetails: "Privacy Policy Details",
    privacyContentNotAvailable: "Privacy policy content is not available at the moment.",
    dataCollectionOverview: "Data Collection Overview",
    whatWeCollect: "What We Collect",
    yourRights: "Your Rights",
    personalInfo: "Personal information and contact details",
    usageData: "Usage data and service interactions",
    technicalData: "Technical data and device information",
    paymentInfo: "Payment information and billing details",
    accessData: "Access your personal data",
    correctData: "Correct inaccurate information",
    deleteData: "Delete your personal data",
    objectProcessing: "Object to data processing",
    privacyQuestions: "Questions About Your Privacy?",
    privacyContactDescription: "Our privacy team is here to help you understand your rights and answer any questions.",
    dataProtectionOfficer: "Data Protection Officer",
    downloadPrivacyPolicy: "Download Privacy Policy",
    requestDataReport: "Request Data Report",
    updatePreferences: "Update Preferences",
     // Disclaimer & Copyright translations
    disclaimerCopyright: "Disclaimer & Copyright",
    disclaimerDescription: "Important legal information about our services and intellectual property",
    importantNotice: "Important Legal Notice",
    disclaimerNotice: "Please read this disclaimer carefully before using our services. By accessing our website and services, you acknowledge and agree to the terms outlined below.",
    liabilityDisclaimer: "Liability Disclaimer",
    liabilityDisclaimerDesc: "We are not liable for any damages resulting from the use of our services",
    copyrightProtection: "Copyright Protection",
    copyrightProtectionDesc: "All content is protected by international copyright laws",
    fairUse: "Fair Use Policy",
    fairUseDesc: "Limited use allowed for educational and personal purposes",
    disclaimerCopyrightDetails: "Disclaimer & Copyright Details",
    legalContentNotAvailable: "Legal content is not available at the moment.",
    copyrightQuickReference: "Copyright Quick Reference",
    allowedUses: "Allowed Uses",
    prohibitedUses: "Prohibited Uses",
    personalUse: "Personal and educational use",
    educationalUse: "Classroom and training use",
    internalBusiness: "Internal business reference",
    attributionRequired: "With proper attribution",
    commercialRedistribution: "Commercial redistribution",
    modification: "Modification or adaptation",
    removalCopyright: "Removal of copyright notices",
    reverseEngineering: "Reverse engineering of software",
    permissionsRequests: "Permissions & Legal Requests",
    permissionsDescription: "Need to use our content or report an infringement? Contact our legal team for permissions and legal inquiries.",
    mailingAddress: "Mailing Address",
    downloadCopyrightPolicy: "Download Copyright Policy",
    requestPermission: "Request Permission",
    reportInfringement: "Report Infringement",
     // Copyright page translations
    copyrightPolicy: "Copyright Policy",
    copyrightDescription: "Protecting our intellectual property and your rights",
    copyrightPolicyDetails: "Copyright Policy Details",
    copyrightContentNotAvailable: "Copyright policy content is not available at the moment.",
    internationalProtection: "International Protection",
    internationalProtectionDesc: "Protected under multiple international copyright treaties",
    dmcaCompliant: "DMCA Compliant",
    dmcaCompliantDesc: "Full compliance with Digital Millennium Copyright Act",
    contactInformation: "Contact Information",
    quickActions: "Quick Actions",
    responseInfo: "Response Information",
    hours: "hours",
    typicalResponse: "Typical response time",
    emergencyResponse: "Emergency infringement reports: 2-4 hours",
    legalProceedings: "Legal proceedings: Immediate action",
    internationalClaims: "International claims: Coordinated response",
     // ... existing translations ...
    cookiePolicy: "Cookie Policy",
    cookieDescription: "Learn how we use cookies to enhance your browsing experience",
    cookiePolicyDetails: "Cookie Policy Details",
    cookieContentNotAvailable: "Cookie policy content is not available at the moment.",
    essentialCookies: "Essential Cookies",
    optionalCookies: "Optional Cookies",
    sessionManagement: "Session management and security",
    securityPurposes: "Security and fraud prevention",
    siteFunctionality: "Core site functionality",
    alwaysActive: "Always active (cannot be disabled)",
    analyticsTracking: "Website analytics and tracking",
    marketingCookies: "Marketing and advertising",
    preferenceCookies: "User preference storage",
    thirdPartyCookies: "Third-party service cookies",
    cookiePreferences: "Cookie Preferences",
    necessaryCookies: "Necessary Cookies",
    necessaryCookiesDesc: "Required for the website to function properly",
    analyticsCookies: "Analytics Cookies",
    analyticsCookiesDesc: "Help us understand how visitors interact with our website",
    marketingCookies: "Marketing Cookies",
    marketingCookiesDesc: "Used to deliver relevant advertisements",
    preferenceCookies: "Preference Cookies",
    preferenceCookiesDesc: "Remember your settings and preferences",
    savePreferences: "Save Preferences",
    clearAllCookies: "Clear All Cookies",
    gdprCompliant: "GDPR Compliant",
    gdprCompliantDesc: "Fully compliant with General Data Protection Regulation",
    transparentUsage: "Transparent Usage",
    transparentUsageDesc: "Clear information about all cookies we use",
    userControl: "User Control",
    userControlDesc: "Full control over your cookie preferences",
    cookieQuestions: "Questions About Cookies?",
    cookieQuestionsDesc: "Our privacy team is here to help you understand our cookie usage and manage your preferences.",
    downloadCookiePolicy: "Download Cookie Policy",
    updatePreferences: "Update Preferences",
    deleteAllData: "Delete All Data",
    urgentRequests: "Urgent requests: 2-4 hours",
    dataBreachReports: "Data breach reports: Immediate action",
    legalInquiries: "Legal inquiries: Coordinated response",
    preferencesSaved: "Your cookie preferences have been saved successfully!",
    confirmClearCookies: "Are you sure you want to clear all cookies? This may affect your browsing experience.",
    cookiesCleared: "All cookies have been cleared successfully.",
    securePaymentTitle: "Secure payment facility",
    securePaymentDesc: "We accept payments securely using American Express, Mastercard, Visa, BAC, and Diners Club."
  },
  es: {
    securePaymentTitle: "Facilidad de Pago Seguro",
    securePaymentDesc: "Aceptamos pagos de forma segura con American Express, Mastercard, Visa, BAC y Diners Club.",
      heroTitlePart1: 'Votre voyage vers le',
    heroTitleHighlight: 'succès',
    heroTitlePart2: 'commence avec nous !',
    heroDescriptionLine1: 'nous permettons aux entreprises de prospérer dans un paysage numérique en évolution rapide',
    heroDescriptionLine2: 'Prêt à vous transformer ? Explorons ensemble comment nous pouvons élever votre organisation.',
     heroTitlePart1: '¡Tu viaje al',
    heroTitleHighlight: 'éxito',
    heroTitlePart2: 'comienza con nosotros!',
    heroDescriptionLine1: 'habilitamos a las empresas para prosperar en un panorama digital en rápida evolución',
    heroDescriptionLine2: '¿Listo para transformarte? Exploremos juntos cómo podemos elevar tu organización.',
    home: 'Inicio',
    about: 'Acerca de',
    services: 'Servicios',
    contact: 'Contacto',
    welcome: 'Bienvenido a nuestro sitio',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    search: 'Buscar...',
    heroTitle: '¡Tu viaje al <span class="text-green-600">éxito</span> comienza con nosotros!',
    heroDescription: 'habilitamos a las empresas para prosperar en un panorama digital en rápida evolución<br />¿Listo para transformarte? Exploremos juntos cómo podemos elevar tu organización.',
    applyOnline: 'solicitar en línea',
    discover: 'Descubrir',
    ellipseAlt: 'Elipse',
    vectorAlt: 'vector',
    planeAlt: 'avión',
    locationAlt: 'ubicación',
    studentAlt: 'Estudiante',
    // Feature Section Localization
      digitalTransformation: 'Transformación Digital',
    digitalTransformationDesc: 'Modernice sus procesos, optimice operaciones y adopte tecnología que impulse la eficiencia y el crecimiento empresarial a largo plazo.',
    boutiqueRecruitment: 'Reclutamiento Especializado',
    boutiqueRecruitmentDesc: 'Encuentre el talento adecuado a través de servicios de reclutamiento personalizados diseñados para construir equipos ágiles y de alto rendimiento para su organización.',
    endToEndSupport: 'Soporte Integral',
    endToEndSupportDesc: 'Desde la estrategia hasta la ejecución, proporcionamos orientación integral y soporte continuo para garantizar una adopción sin problemas y resultados sostenibles.',
    learnMore: 'Saber Más',
    graduationAlt: 'gorro de graduación',
     // Feedback section translations
    quickIntro: 'Introducción Rápida',
    quickIntroTitle: 'Aquí tienes una breve introducción sobre nosotros',
    introVideoTitle: 'Video de Introducción de la Empresa',
    videoNotSupported: 'Tu navegador no soporta la etiqueta de video.',
     // Partners section translations
    ourPartners: 'Nuestros Socios',
    partnersDescription: 'Contamos con socios de calidad en una variedad de destinos alrededor del mundo.',
    bacAlt: 'BAC',
    cloudCredentialAlt: 'Consejo de Credenciales en la Nube',
    dinersClubAlt: 'Diners Club',
    discoverAlt: 'Discover',
    lssiAlt: 'LSSI',
    amaAlt: 'Asociación Americana de Marketing',
    pdtsAlt: 'PDTS',
    mountainAlt: 'montaña',
      // Certifications section translations
    ourSpecializations: 'NUESTRAS ESPECIALIZACIONES',
    popularCertifications: 'Certificaciones',
    internationalCertifications: 'Certificaciones Internacionales',
    executivePrograms: 'Programas Ejecutivos',
    // International Certifications
    microsoftAzure: 'Microsoft Azure',
    devops: 'DevOps',
    networkEngineering: 'Ingeniería de Redes',
    windowsServer: 'Windows Server',
    dataEngineering: 'Ingeniería de Datos',
    microsoftDynamics: 'Microsoft Dynamics',
    microsoft365: 'Microsoft 365',
    microsoftTeams: 'Microsoft Teams',
    msPowerPlatform: 'MS Power Platform',
    cyberSecurity: 'Ciberseguridad',
    management: 'Gestión',
    leanSixSigma: 'Instituto Lean Six Sigma',
    agileCertifications: 'Certificaciones Ágiles',
    scrumCertification: 'Certificación Scrum',
    // Executive Programs
    python: 'Python',
    sql: 'SQL',
    javascript: 'JavaScript',
    html: 'HTML',
    css: 'CSS',
    java: 'Java',
    r: 'R',
    excel: 'Excel',
    php: 'PHP',
    swift: 'Swift',
    c: 'C',
    powerBI: 'Power BI',
    reactNative: 'React Native',
    nodejs: 'Nodejs',
       // Steps section translations
    stepsTitle: 'PASOS',
    stepsSubtitle: 'Pasos para obtener tu certificación',
    stepsDescription: 'Sigue este simple proceso de 5 pasos para lograr tu certificación y desbloquear nuevas oportunidades profesionales',
    exploreCertifications: 'Explora Certificaciones',
    exploreCertificationsDesc: 'Navega por nuestra amplia gama de programas de certificación y encuentra el perfecto para tus objetivos profesionales.',
    enrollYourself: 'Inscríbete',
    enrollYourselfDesc: 'Elige tu programa y completa el sencillo proceso de inscripción para comenzar inmediatamente.',
    attendClasses: 'Asiste a Clases',
    attendClassesDesc: 'Participa en clases interactivas en línea o presenciales con instructores expertos.',
    completeTasks: 'Completa Tareas',
    completeTasksDesc: 'Termina asignaciones, ejercicios prácticos y proyectos para demostrar tus habilidades.',
    getCertified: 'Certifícate',
    getCertifiedDesc: 'Recibe tu certificación reconocida por la industria y lleva tu carrera al siguiente nivel.',
     // FAQ Questions and Answers
    faqQuestion1: '¿Cómo obtener admisión en una universidad en el extranjero?',
    faqAnswer1: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
    faqQuestion2: '¿Ofrecen solución completa para estudiantes?',
    faqAnswer2: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
    faqQuestion3: '¿Qué país es seguro y mejor para estudios superiores?',
    faqAnswer3: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
    faqQuestion4: '¿Qué país ofrece residencia permanente después de estudiar y conseguir trabajo?',
    faqAnswer4: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
    faqQuestion5: '¿Puedo obtener una beca con mi bajo promedio de calificaciones?',
    faqAnswer5: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
    faqQuestion6: '¿Ofrecen alojamiento para estudiantes en el extranjero?',
    faqAnswer6: 'Noruega, USA, Reino Unido, Alemania e Italia son los países más seguros del mundo para estudiantes de Bangladesh para estudios superiores.',
     // Footer translations
    newsletterTitle: 'Suscríbete a nuestro boletín',
    newsletterDescription: 'Mantente actualizado con nuestras últimas ofertas, oportunidades de estudio en el extranjero y perspectivas educativas',
    emailPlaceholder: 'Ingresa tu dirección de correo electrónico',
    subscribe: 'Suscribirse',
    companyLogoAlt: 'Logo de Tara Solutions',
    bellIconAlt: 'Icono de campana',
    aboutSectionTitle: 'Acerca de Tara Solutions',
    aboutDescription: 'Estamos especializados en formación corporativa y cursos líderes en la industria',
    educationAwardAlt: 'Premio de Educación',
    isoCertifiedAlt: 'Certificado ISO',
    corporateSectionTitle: 'Corporativo',
    termsConditions: 'Términos y Condiciones',
    disclaimerCopyright: 'Descargo de responsabilidad y Copyright',
    cookiePolicy: 'Política de Cookies',
    privacyPolicy: 'Política de Privacidad',
    quickLinksTitle: 'Enlaces Rápidos',
    aboutUs: 'Acerca de Nosotros',
    getInTouchTitle: 'Ponte en Contacto',
    locationAlt: 'Ubicación',
    companyAddress: 'Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7',
    followUs: 'Síguenos',
    copyrightText: '© 2025 Tara Solutions. Todos los derechos reservados | Desarrollado por',
    companyName: 'Tara Solutions',
    // About page translations
    aboutHeroBadge: 'Consultoría Educativa Líder',
    aboutHeroTitle: 'Moldeando Futuros a Través de la Educación Global',
    aboutHeroDescription1: 'Eduplan es una firma de consultoría educativa internacional de primer nivel dedicada a guiar a los estudiantes hacia sus sueños académicos en las mejores universidades del mundo.',
    aboutHeroDescription2: 'Con nuestra sede en India, nos especializamos en asegurar admisiones para estudiantes en instituciones prestigiosas en Reino Unido, USA, Australia, Canadá, Alemania, Suecia, y nuestras universidades asociadas en Malasia, Chipre y China.',
    lifetimeAccess: 'Acceso de por Vida',
    lifetimeAccessDesc: 'Pago único para acceso ilimitado a cursos. ¡Simple y efectivo!',
    lifetimeAccessAlt: 'Acceso de por Vida',
    expertTutors: 'Tutores Expertos',
    expertTutorsDesc: 'Aprende de expertos de la industria con amplia experiencia docente',
    expertTutorsAlt: 'Tutores Expertos',
    practicalCurriculum: 'Plan de Estudios Práctico',
    practicalCurriculumDesc: 'Cursos de clase mundial con proyectos prácticos que construyen confianza',
    practicalLearningAlt: 'Aprendizaje Práctico',
    getFreeConsultation: 'Obtener Consulta Gratuita',
    exploreCourses: 'Explorar Cursos',
    modernCampusAlt: 'Campus Moderno',
    successRateAlt: 'Tasa de Éxito',
    successRate: 'Tasa de Éxito',
    studentsGuided: 'Estudiantes Guiados',
    expertConsultants: 'Consultores Expertos',
    coursesOffered: 'Cursos Ofrecidos',
    ourCommitment: 'Nuestro Compromiso',
    missionVisionTitle: 'Construyendo Puentes hacia la Educación Global',
    missionVisionStats: '87% de los estudiantes que eligen Eduplan reportan avances significativos en sus carreras y crecimiento personal.',
    ourVision: 'Nuestra Visión',
    ourVisionDesc: 'Ser la consultoría estudiantil líder mundial, transformando vidas a través de oportunidades de educación global accesibles.',
    ourMission: 'Nuestra Misión',
    ourMissionDesc: 'Lograr la excelencia a través de servicios innovadores que hagan la educación de clase mundial accesible dentro de la capacidad de cada estudiante.',
    ourGoal: 'Nuestra Meta',
    ourGoalDesc: 'Crear oportunidades de estudio internacional que mejoren el crecimiento individual y contribuyan al desarrollo nacional.',
    successStories: 'HISTORIAS DE ÉXITO',
    testimonialsTitle: 'Estudiantes que Alcanzaron el Éxito Globalmente',
    testimonialsDescription: 'Escucha a nuestros estudiantes que han transformado sus vidas a través de la educación internacional',
    testimonial1: 'Eduplan me ayudó a asegurar la admisión en mi universidad soñada en el Reino Unido. ¡La guía fue excepcional de principio a fin!',
    testimonial2: 'Los consultores de Eduplan son verdaderamente expertos. Hicieron que el complejo proceso de visa fuera simple y directo.',
    testimonial3: 'Gracias a Eduplan, ahora estudio en una de las mejores universidades canadienses. Su apoyo marcó la diferencia en mi viaje.',
    testimonial4: 'La orientación sobre becas que recibí fue invaluable. Eduplan me ayudó a asegurar fondos que ni siquiera sabía que estaban disponibles.',
    ctaTitle: '¿Listo para Comenzar tu Viaje de Educación Global?',
    ctaDescription: 'Únete a miles de estudiantes exitosos que han transformado sus vidas con la guía experta de Eduplan.',
    startFreeConsultation: 'Comenzar Consulta Gratuita',
    browseCourses: 'Explorar Cursos',
     // Course listing translations
    courseListingTitle: 'Tenemos {count} cursos en total',
    courseListingDescription: 'Tenemos alianzas profesionales con las principales universidades y colegios de todo el mundo.',
    category: 'Categoría',
    certifier: 'Certificador',
    duration: 'Duración',
    modality: 'Modalidad',
    select: 'Seleccionar',
    filter: 'Filtrar',
    reset: 'Restablecer',
    bookMySeat: 'Reservar Mi Cupo',
    courseDefaultDescription: 'Curso diseñado para profesionales que buscan certificación.',
    bookYourSeat: 'Reservar Tu Cupo',
    course: 'Curso',
    fullName: 'Nombre Completo',
    enterFullName: 'Ingresa tu nombre completo',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    phonePlaceholder: '+52 XXX XXXXXXX',
    message: 'Mensaje',
    messagePlaceholder: 'Cualquier requisito especial o pregunta...',
    sendInquiry: 'Enviar Consulta',
    inquirySentSuccess: '¡Consulta Enviada Exitosamente!',
    thankYouMessage: 'Gracias por tu interés. Nos pondremos en contacto contigo pronto.',
    prev: 'ANTERIOR',
    next: 'SIGUIENTE',
     // Courses page translations
    exclusivePrograms: 'Programas Exclusivos',
    executivePrograms: 'Programas Ejecutivos',
    executiveProgramsDescription: 'Programas de liderazgo avanzado diseñados para profesionales senior que buscan crecimiento transformador e impacto estratégico.',
    allCourses: 'Todos los Cursos',
    findPerfectCourse: 'Encuentra el curso perfecto para mejorar tus habilidades',
    searchCourses: 'Buscar cursos...',
    category: 'Categoría',
    allCategories: 'Todas las Categorías',
    technology: 'Tecnología',
    allTechnologies: 'Todas las Tecnologías',
    applyFilters: 'Aplicar Filtros',
    resetAll: 'Restablecer Todo',
    coursesCount: 'Cursos',
    available: 'Disponibles',
    noCoursesFound: 'No se encontraron cursos',
    adjustSearchCriteria: 'Intenta ajustar tus criterios de búsqueda o filtros',
    resetFilters: 'Restablecer Filtros',
    bookMySeat: 'Reservar Mi Cupo',
    bookYourSeat: 'Reservar Tu Cupo',
    course: 'Curso',
    courseDetails: 'Detalles del Curso',
    description: 'Descripción',
    careerOpportunities: 'Oportunidades de Carrera',
    fullName: 'Nombre Completo',
    enterFullName: 'Ingresa tu nombre completo',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    phonePlaceholder: '+52 XXX XXXXXXX',
    message: 'Mensaje',
    messagePlaceholder: 'Cualquier requisito especial o pregunta...',
    sending: 'Enviando...',
    sendInquiry: 'Enviar Consulta',
    inquirySentSuccess: '¡Consulta Enviada Exitosamente!',
    thankYouMessage: 'Gracias por tu interés. Nos pondremos en contacto contigo pronto.',
    close: 'Cerrar',
    previous: 'Anterior',
    next: 'Siguiente',
     // Contact page translations
    contactHeroTitle: "Conectemos",
    contactHeroDescription: "¿Listo para comenzar tu viaje? Estamos aquí para ayudarte en cada paso. Ponte en contacto con nuestro equipo dedicado hoy.",
    responseTime: "Normalmente respondemos en 2 horas",
    getInTouch: "Ponte en Contacto",
    getInTouchDescription: "Nos encantaría saber de ti. Envíanos un mensaje y responderemos lo antes posible.",
    ourOffice: "Nuestra Oficina",
    officeAddress: "Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7",
    phoneNumbers: "Números de Teléfono",
    phoneDetails: "+506 8701-6253 & +507 6473-6099",
    emailAddress: "Correo Electrónico",
    emailDetails: "info@tarasolutions-cr.com & gerencia@tarasolutions-cr.com",
    businessHours: "Horario Comercial",
    businessHoursDetails: "Lun - Vie: 9:00 AM - 6:00 PM Sáb: 10:00 AM - 4:00 PM",
    followUs: "Síguenos",
    supportAvailable: "24/7",
    support: "Soporte Disponible",
    avgResponseTime: "2h",
    responseTimeLabel: "Tiempo Promedio de Respuesta",
    sendMessage: "Envíanos un Mensaje",
    sendMessageDescription: "Completa el formulario a continuación y nos pondremos en contacto contigo pronto.",
    personalInformation: "Información Personal",
    fullName: "Nombre completo",
    phoneNumber: "Número de teléfono",
    subject: "Asunto",
    yourMessage: "Tu Mensaje",
    messagePlaceholder: "Cuéntanos sobre tu consulta...",
    sendMessageButton: "Enviar Mensaje",
    visitOurCampus: "Visita Nuestro Campus",
    campusDescription: "Ubicado en el corazón de la ciudad, nuestro campus es de fácil acceso y está equipado con instalaciones de última generación.",
      // Terms and Conditions translations
    termsAndConditions: "Términos y Condiciones",
    termsDescription: "Por favor lea estos términos cuidadosamente antes de usar nuestros servicios",
    lastUpdated: "Última Actualización",
    dataProtection: "Protección de Datos",
    dataProtectionDesc: "Su información personal está asegurada con encriptación de nivel empresarial",
    userRights: "Derechos del Usuario",
    userRightsDesc: "Pautas claras sobre sus derechos y responsabilidades",
    transparentTerms: "Términos Transparentes",
    transparentTermsDesc: "Sin cláusulas ocultas ni jerga legal complicada",
    termsOfService: "Términos de Servicio",
    termsContentNotAvailable: "El contenido de términos y condiciones no está disponible en este momento.",
    acceptanceTitle: "¿Listo para Comenzar?",
    acceptanceDescription: "Al continuar usando nuestros servicios, usted reconoce que ha leído y acepta nuestros Términos y Condiciones.",
    acceptTerms: "Acepto los Términos",
    downloadPDF: "Descargar Versión PDF",
     // Privacy Policy translations
    privacyPolicy: "Política de Privacidad",
    privacyDescription: "Aprenda cómo protegemos y gestionamos su información personal",
    dataSecurity: "Seguridad de Datos",
    dataSecurityDesc: "Encriptación de nivel empresarial y protocolos de seguridad",
    yourControl: "Su Control",
    yourControlDesc: "Control total sobre sus datos personales y preferencias",
    transparency: "Transparencia",
    transparencyDesc: "Información clara sobre recopilación y uso de datos",
    privacyPolicyDetails: "Detalles de la Política de Privacidad",
    privacyContentNotAvailable: "El contenido de la política de privacidad no está disponible en este momento.",
    dataCollectionOverview: "Resumen de Recopilación de Datos",
    whatWeCollect: "Lo que Recopilamos",
    yourRights: "Sus Derechos",
    personalInfo: "Información personal y datos de contacto",
    usageData: "Datos de uso e interacciones con el servicio",
    technicalData: "Datos técnicos e información del dispositivo",
    paymentInfo: "Información de pago y detalles de facturación",
    accessData: "Acceder a sus datos personales",
    correctData: "Corregir información inexacta",
    deleteData: "Eliminar sus datos personales",
    objectProcessing: "Oponerse al procesamiento de datos",
    privacyQuestions: "¿Preguntas Sobre Su Privacidad?",
    privacyContactDescription: "Nuestro equipo de privacidad está aquí para ayudarle a comprender sus derechos y responder cualquier pregunta.",
    dataProtectionOfficer: "Oficial de Protección de Datos",
    downloadPrivacyPolicy: "Descargar Política de Privacidad",
    requestDataReport: "Solicitar Informe de Datos",
    updatePreferences: "Actualizar Preferencias",
    // Disclaimer & Copyright translations
    disclaimerCopyright: "Descargo de Responsabilidad y Derechos de Autor",
    disclaimerDescription: "Información legal importante sobre nuestros servicios y propiedad intelectual",
    importantNotice: "Aviso Legal Importante",
    disclaimerNotice: "Por favor lea este descargo de responsabilidad cuidadosamente antes de usar nuestros servicios. Al acceder a nuestro sitio web y servicios, usted reconoce y acepta los términos descritos a continuación.",
    liabilityDisclaimer: "Descargo de Responsabilidad",
    liabilityDisclaimerDesc: "No somos responsables por ningún daño resultante del uso de nuestros servicios",
    copyrightProtection: "Protección de Derechos de Autor",
    copyrightProtectionDesc: "Todo el contenido está protegido por leyes internacionales de derechos de autor",
    fairUse: "Política de Uso Justo",
    fairUseDesc: "Uso limitado permitido para fines educativos y personales",
    disclaimerCopyrightDetails: "Detalles de Descargo y Derechos de Autor",
    legalContentNotAvailable: "El contenido legal no está disponible en este momento.",
    copyrightQuickReference: "Referencia Rápida de Derechos de Autor",
    allowedUses: "Usos Permitidos",
    prohibitedUses: "Usos Prohibidos",
    personalUse: "Uso personal y educativo",
    educationalUse: "Uso en aula y formación",
    internalBusiness: "Referencia interna de negocios",
    attributionRequired: "Con atribución adecuada",
    commercialRedistribution: "Redistribución comercial",
    modification: "Modificación o adaptación",
    removalCopyright: "Eliminación de avisos de derechos de autor",
    reverseEngineering: "Ingeniería inversa de software",
    permissionsRequests: "Permisos y Solicitudes Legales",
    permissionsDescription: "¿Necesita usar nuestro contenido o reportar una infracción? Contacte a nuestro equipo legal para permisos y consultas legales.",
    mailingAddress: "Dirección Postal",
    downloadCopyrightPolicy: "Descargar Política de Derechos de Autor",
    requestPermission: "Solicitar Permiso",
    reportInfringement: "Reportar Infracción",
     // Copyright page translations
    copyrightPolicy: "Política de Derechos de Autor",
    copyrightDescription: "Protegiendo nuestra propiedad intelectual y sus derechos",
    copyrightPolicyDetails: "Detalles de la Política de Derechos de Autor",
    copyrightContentNotAvailable: "El contenido de la política de derechos de autor no está disponible en este momento.",
    internationalProtection: "Protección Internacional",
    internationalProtectionDesc: "Protegido bajo múltiples tratados internacionales de derechos de autor",
    dmcaCompliant: "Cumplimiento DMCA",
    dmcaCompliantDesc: "Cumplimiento total con la Ley de Derechos de Autor de la Era Digital",
    contactInformation: "Información de Contacto",
    quickActions: "Acciones Rápidas",
    responseInfo: "Información de Respuesta",
    hours: "horas",
    typicalResponse: "Tiempo de respuesta típico",
    emergencyResponse: "Informes de infracción de emergencia: 2-4 horas",
    legalProceedings: "Procedimientos legales: Acción inmediata",
    internationalClaims: "Reclamos internacionales: Respuesta coordinada",
     // ... existing Spanish translations ...
    cookiePolicy: "Política de Cookies",
    cookieDescription: "Aprenda cómo utilizamos las cookies para mejorar su experiencia de navegación",
    cookiePolicyDetails: "Detalles de la Política de Cookies",
    cookieContentNotAvailable: "El contenido de la política de cookies no está disponible en este momento.",
    essentialCookies: "Cookies Esenciales",
    optionalCookies: "Cookies Opcionales",
    sessionManagement: "Gestión de sesión y seguridad",
    securityPurposes: "Seguridad y prevención de fraudes",
    siteFunctionality: "Funcionalidad básica del sitio",
    alwaysActive: "Siempre activas (no se pueden desactivar)",
    analyticsTracking: "Análisis web y seguimiento",
    marketingCookies: "Marketing y publicidad",
    preferenceCookies: "Almacenamiento de preferencias",
    thirdPartyCookies: "Cookies de servicios de terceros",
    cookiePreferences: "Preferencias de Cookies",
    necessaryCookies: "Cookies Necesarias",
    necessaryCookiesDesc: "Requeridas para que el sitio web funcione correctamente",
    analyticsCookies: "Cookies de Análisis",
    analyticsCookiesDesc: "Nos ayudan a entender cómo interactúan los visitantes con nuestro sitio web",
    marketingCookies: "Cookies de Marketing",
    marketingCookiesDesc: "Utilizadas para mostrar anuncios relevantes",
    preferenceCookies: "Cookies de Preferencias",
    preferenceCookiesDesc: "Recuerdan sus configuraciones y preferencias",
    savePreferences: "Guardar Preferencias",
    clearAllCookies: "Borrar Todas las Cookies",
    gdprCompliant: "Cumplimiento GDPR",
    gdprCompliantDesc: "Totalmente conforme con el Reglamento General de Protección de Datos",
    transparentUsage: "Uso Transparente",
    transparentUsageDesc: "Información clara sobre todas las cookies que utilizamos",
    userControl: "Control del Usuario",
    userControlDesc: "Control total sobre sus preferencias de cookies",
    cookieQuestions: "¿Preguntas Sobre Cookies?",
    cookieQuestionsDesc: "Nuestro equipo de privacidad está aquí para ayudarle a entender nuestro uso de cookies y gestionar sus preferencias.",
    downloadCookiePolicy: "Descargar Política de Cookies",
    updatePreferences: "Actualizar Preferencias",
    deleteAllData: "Eliminar Todos los Datos",
    urgentRequests: "Solicitudes urgentes: 2-4 horas",
    dataBreachReports: "Informes de violación de datos: Acción inmediata",
    legalInquiries: "Consultas legales: Respuesta coordinada",
    preferencesSaved: "¡Sus preferencias de cookies se han guardado correctamente!",
    confirmClearCookies: "¿Está seguro de que desea borrar todas las cookies? Esto puede afectar su experiencia de navegación.",
    cookiesCleared: "Todas las cookies se han borrado correctamente.",
  },
  // fr: {
  //   home: 'Accueil',
  //   about: 'À propos',
  //   services: 'Services',
  //   contact: 'Contact',
  //   welcome: 'Bienvenue sur notre site',
  //   login: 'Connexion',
  //   signup: "S'inscrire",
  //   search: 'Rechercher...',
  //   heroTitle: 'Votre voyage vers le <span class="text-green-600">succès</span> commence avec nous !',
  //   heroDescription: 'nous permettons aux entreprises de prospérer dans un paysage numérique en évolution rapide<br />Prêt à vous transformer ? Explorons ensemble comment nous pouvons élever votre organisation.',
  //   applyOnline: 'postuler en ligne',
  //   discover: 'Découvrir',
  //   ellipseAlt: 'Ellipse',
  //   vectorAlt: 'vecteur',
  //   planeAlt: 'avion',
  //   locationAlt: 'localisation',
  //   studentAlt: 'Étudiant',
  //   // Feature Section Localization
  //     digitalTransformation: 'Transformation Digitale',
  //   digitalTransformationDesc: 'Modernisez vos processus, rationalisez les opérations et adoptez une technologie qui stimule l\'efficacité et la croissance commerciale à long terme.',
  //   boutiqueRecruitment: 'Recrutement Sur Mesure',
  //   boutiqueRecruitmentDesc: 'Trouvez les bons talents grâce à des services de recrutement personnalisés conçus pour constituer des équipes agiles et performantes pour votre organisation.',
  //   endToEndSupport: 'Support Complet',
  //   endToEndSupportDesc: 'De la stratégie à l\'exécution, nous fournissons des conseils complets et un support continu pour assurer une adoption fluide et des résultats durables.',
  //   learnMore: 'En Savoir Plus',
  //   graduationAlt: 'casquette de graduation',
  //      // Feedback section translations
  //   quickIntro: 'Introduction Rapide',
  //   quickIntroTitle: 'Voici une brève introduction sur nous',
  //   introVideoTitle: 'Vidéo de Présentation de l\'Entreprise',
  //   videoNotSupported: 'Votre navigateur ne prend pas en charge la balise vidéo.',
  //     // Partners section translations
  //   ourPartners: 'Nos Partenaires',
  //   partnersDescription: 'Nous avons des partenaires de qualité dans diverses destinations à travers le monde.',
  //   bacAlt: 'BAC',
  //   cloudCredentialAlt: 'Conseil des Accréditations Cloud',
  //   dinersClubAlt: 'Diners Club',
  //   discoverAlt: 'Discover',
  //   lssiAlt: 'LSSI',
  //   amaAlt: 'Association Américaine du Marketing',
  //   pdtsAlt: 'PDTS',
  //   mountainAlt: 'montagne',
  //    // Certifications section translations
  //   ourSpecializations: 'NUESTRAS ESPECIALIZACIONES',
  //   popularCertifications: 'Certificaciones',
  //   internationalCertifications: 'Certificaciones Internacionales',
  //   executivePrograms: 'Programas Ejecutivos',
  //     // Certifications section translations
  //   ourSpecializations: 'NOS SPÉCIALISATIONS',
  //   popularCertifications: 'Certifications',
  //   internationalCertifications: 'Certifications Internationales',
  //   executivePrograms: 'Programmes Exécutifs',
  //   // International Certifications
  //   microsoftAzure: 'Microsoft Azure',
  //   devops: 'DevOps',
  //   networkEngineering: 'Ingénierie Réseau',
  //   windowsServer: 'Windows Server',
  //   dataEngineering: 'Ingénierie des Données',
  //   microsoftDynamics: 'Microsoft Dynamics',
  //   microsoft365: 'Microsoft 365',
  //   microsoftTeams: 'Microsoft Teams',
  //   msPowerPlatform: 'MS Power Platform',
  //   cyberSecurity: 'Cybersécurité',
  //   management: 'Management',
  //   leanSixSigma: 'Institut Lean Six Sigma',
  //   agileCertifications: 'Certifications Agile',
  //   scrumCertification: 'Certification Scrum',
  //   // Executive Programs
  //   python: 'Python',
  //   sql: 'SQL',
  //   javascript: 'JavaScript',
  //   html: 'HTML',
  //   css: 'CSS',
  //   java: 'Java',
  //   r: 'R',
  //   excel: 'Excel',
  //   php: 'PHP',
  //   swift: 'Swift',
  //   c: 'C',
  //   powerBI: 'Power BI',
  //   reactNative: 'React Native',
  //   nodejs: 'Nodejs',
  //     // Steps section translations
  //   stepsTitle: 'ÉTAPES',
  //   stepsSubtitle: 'Étapes pour obtenir votre certification',
  //   stepsDescription: 'Suivez ce simple processus en 5 étapes pour obtenir votre certification et débloquer de nouvelles opportunités de carrière',
  //   exploreCertifications: 'Explorez les Certifications',
  //   exploreCertificationsDesc: 'Parcourez notre large gamme de programmes de certification et trouvez celui qui correspond parfaitement à vos objectifs de carrière.',
  //   enrollYourself: 'Inscrivez-vous',
  //   enrollYourselfDesc: 'Choisissez votre programme et complétez le processus d\'inscription simple pour commencer immédiatement.',
  //   attendClasses: 'Assistez aux Cours',
  //   attendClassesDesc: 'Participez à des cours interactifs en ligne ou en présentiel avec des instructeurs experts.',
  //   completeTasks: 'Complétez les Tâches',
  //   completeTasksDesc: 'Terminez les devoirs, exercices pratiques et projets pour démontrer vos compétences.',
  //   getCertified: 'Certifié',
  //   getCertifiedDesc: 'Recevez votre certification reconnue par l\'industrie et faites passer votre carrière au niveau supérieur.',
  //     // FAQ section translations
  //   faqTitle: 'FAQ',
  //   faqSubtitle: 'Questions fréquemment posées',
  //   faqDescriptionLine1: 'Vous avez encore des questions à poser ?',
  //   faqDescriptionLine2: 'N\'hésitez pas à demander à nos experts ici.',
  //   askYourQuestions: 'POSEZ VOS QUESTIONS',
  //   // FAQ Questions and Answers
  //   faqQuestion1: 'Comment obtenir l\'admission dans une université à l\'étranger ?',
  //   faqAnswer1: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //   faqQuestion2: 'Offrez-vous une solution complète pour les étudiants ?',
  //   faqAnswer2: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //   faqQuestion3: 'Quel pays est sûr et meilleur pour les études supérieures ?',
  //   faqAnswer3: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //   faqQuestion4: 'Quel pays offre la résidence permanente après les études et l\'obtention d\'un emploi ?',
  //   faqAnswer4: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //   faqQuestion5: 'Puis-je obtenir une bourse avec ma faible moyenne cumulative ?',
  //   faqAnswer5: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //   faqQuestion6: 'Proposez-vous un hébergement pour les étudiants à l\'étranger ?',
  //   faqAnswer6: 'La Norvège, les États-Unis, le Royaume-Uni, l\'Allemagne et l\'Italie sont les pays les plus sûrs au monde pour les étudiants bangladais pour les études supérieures.',
  //    // Footer translations
  //   newsletterTitle: 'Abonnez-vous à notre newsletter',
  //   newsletterDescription: 'Restez informé de nos dernières offres, opportunités d\'études à l\'étranger et perspectives éducatives',
  //   emailPlaceholder: 'Entrez votre adresse email',
  //   subscribe: 'S\'abonner',
  //   companyLogoAlt: 'Logo Tara Solutions',
  //   bellIconAlt: 'Icône de cloche',
  //   aboutSectionTitle: 'À propos de Tara Solutions',
  //   aboutDescription: 'Nous sommes spécialisés dans la formation d\'entreprise et les cours leaders de l\'industrie',
  //   educationAwardAlt: 'Prix de l\'Éducation',
  //   isoCertifiedAlt: 'Certifié ISO',
  //   corporateSectionTitle: 'Entreprise',
  //   termsConditions: 'Termes et Conditions',
  //   disclaimerCopyright: 'Avertissement et Copyright',
  //   cookiePolicy: 'Politique des Cookies',
  //   privacyPolicy: 'Politique de Confidentialité',
  //   quickLinksTitle: 'Liens Rapides',
  //   aboutUs: 'À propos de nous',
  //   getInTouchTitle: 'Entrer en Contact',
  //   locationAlt: 'Localisation',
  //   companyAddress: 'Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7',
  //   followUs: 'Suivez-nous',
  //   copyrightText: '© 2025 Tara Solutions. Tous droits réservés | Développé par',
  //   companyName: 'Tara Solutions',
  //    // About page translations
  //   aboutHeroBadge: 'Conseil en Éducation Leader',
  //   aboutHeroTitle: 'Façonner l\'Avenir par l\'Éducation Mondiale',
  //   aboutHeroDescription1: 'Eduplan est une firme de conseil en éducation internationale de premier plan dédiée à guider les étudiants vers leurs rêves académiques dans les meilleures universités mondiales.',
  //   aboutHeroDescription2: 'Avec notre siège en Inde, nous nous spécialisons dans l\'obtention d\'admissions pour les étudiants dans des institutions prestigieuses au Royaume-Uni, USA, Australie, Canada, Allemagne, Suède, et nos universités partenaires en Malaisie, Chypre et Chine.',
  //   lifetimeAccess: 'Accès à Vie',
  //   lifetimeAccessDesc: 'Paiement unique pour un accès illimité aux cours. Simple et efficace !',
  //   lifetimeAccessAlt: 'Accès à Vie',
  //   expertTutors: 'Tuteurs Experts',
  //   expertTutorsDesc: 'Apprenez auprès d\'experts de l\'industrie avec une vaste expérience d\'enseignement',
  //   expertTutorsAlt: 'Tuteurs Experts',
  //   practicalCurriculum: 'Programme Pratique',
  //   practicalCurriculumDesc: 'Cours de classe mondiale avec des projets pratiques qui renforcent la confiance',
  //   practicalLearningAlt: 'Apprentissage Pratique',
  //   getFreeConsultation: 'Obtenir une Consultation Gratuite',
  //   exploreCourses: 'Explorer les Cours',
  //   modernCampusAlt: 'Campus Moderne',
  //   successRateAlt: 'Taux de Réussite',
  //   successRate: 'Taux de Réussite',
  //   studentsGuided: 'Étudiants Guidés',
  //   expertConsultants: 'Conseillers Experts',
  //   coursesOffered: 'Cours Proposés',
  //   ourCommitment: 'Notre Engagement',
  //   missionVisionTitle: 'Construire des Ponts vers l\'Éducation Mondiale',
  //   missionVisionStats: '87% des étudiants qui choisissent Eduplan rapportent des avancées significatives dans leur carrière et leur croissance personnelle.',
  //   ourVision: 'Notre Vision',
  //   ourVisionDesc: 'Être le conseil étudiant leader mondial, transformant des vies grâce à des opportunités d\'éducation mondiale accessibles.',
  //   ourMission: 'Notre Mission',
  //   ourMissionDesc: 'Atteindre l\'excellence grâce à des services innovants qui rendent l\'éducation de classe mondiale accessible dans la capacité de chaque étudiant.',
  //   ourGoal: 'Notre Objectif',
  //   ourGoalDesc: 'Créer des opportunités d\'étude internationales qui améliorent la croissance individuelle et contribuent au développement national.',
  //   successStories: 'HISTOIRES DE RÉUSSITE',
  //   testimonialsTitle: 'Étudiants qui ont Réussi à l\'International',
  //   testimonialsDescription: 'Écoutez nos étudiants qui ont transformé leur vie grâce à l\'éducation internationale',
  //   testimonial1: 'Eduplan m\'a aidé à obtenir l\'admission dans mon université de rêve au Royaume-Uni. L\'accompagnement a été exceptionnel du début à la fin !',
  //   testimonial2: 'Les conseillers d\'Eduplan sont vraiment des experts. Ils ont rendu le processus complexe de visa simple et direct.',
  //   testimonial3: 'Grâce à Eduplan, j\'étudie maintenant dans une université canadienne de premier plan. Leur soutien a fait toute la différence dans mon parcours.',
  //   testimonial4: 'Les conseils sur les bourses que j\'ai reçus étaient inestimables. Eduplan m\'a aidé à obtenir des financements dont je ne connaissais même pas l\'existence.',
  //   ctaTitle: 'Prêt à Commencer Votre Parcours d\'Éducation Mondiale ?',
  //   ctaDescription: 'Rejoignez des milliers d\'étudiants qui ont transformé leur vie avec l\'accompagnement expert d\'Eduplan.',
  //   startFreeConsultation: 'Commencer une Consultation Gratuite',
  //   browseCourses: 'Parcourir les Cours',
  //    courseListingTitle: 'Nous avons {count} cours au total',
  //   courseListingDescription: 'Nous avons des alliances professionnelles avec les principales universités et collèges du monde entier.',
  //   category: 'Catégorie',
  //   certifier: 'Organisme de Certification',
  //   duration: 'Durée',
  //   modality: 'Modalité',
  //   select: 'Sélectionner',
  //   filter: 'Filtrer',
  //   reset: 'Réinitialiser',
  //   bookMySeat: 'Réserver Ma Place',
  //   courseDefaultDescription: 'Cours conçu pour les professionnels cherchant une certification.',
  //   bookYourSeat: 'Réserver Votre Place',
  //   course: 'Cours',
  //   fullName: 'Nom Complet',
  //   enterFullName: 'Entrez votre nom complet',
  //   email: 'Email',
  //   phone: 'Téléphone',
  //   phonePlaceholder: '+33 X XX XX XX XX',
  //   message: 'Message',
  //   messagePlaceholder: 'Toute exigence spéciale ou question...',
  //   sendInquiry: 'Envoyer la Demande',
  //   inquirySentSuccess: 'Demande Envoyée avec Succès !',
  //   thankYouMessage: 'Merci pour votre intérêt. Nous vous recontacterons bientôt.',
  //   prev: 'PRÉCÉDENT',
  //   next: 'SUIVANT',
  //   // Courses page translations
  //   exclusivePrograms: 'Programmes Exclusifs',
  //   executivePrograms: 'Programmes Exécutifs',
  //   executiveProgramsDescription: 'Programmes de leadership avancé conçus pour les professionnels seniors recherchant une croissance transformative et un impact stratégique.',
  //   allCourses: 'Tous les Cours',
  //   findPerfectCourse: 'Trouvez le cours parfait pour développer vos compétences',
  //   searchCourses: 'Rechercher des cours...',
  //   category: 'Catégorie',
  //   allCategories: 'Toutes les Catégories',
  //   technology: 'Technologie',
  //   allTechnologies: 'Toutes les Technologies',
  //   applyFilters: 'Appliquer les Filtres',
  //   resetAll: 'Tout Réinitialiser',
  //   coursesCount: 'Cours',
  //   available: 'Disponibles',
  //   noCoursesFound: 'Aucun cours trouvé',
  //   adjustSearchCriteria: 'Essayez d\'ajuster vos critères de recherche ou filtres',
  //   resetFilters: 'Réinitialiser les Filtres',
  //   bookMySeat: 'Réserver Ma Place',
  //   bookYourSeat: 'Réserver Votre Place',
  //   course: 'Cours',
  //   courseDetails: 'Détails du Cours',
  //   description: 'Description',
  //   careerOpportunities: 'Opportunités de Carrière',
  //   fullName: 'Nom Complet',
  //   enterFullName: 'Entrez votre nom complet',
  //   email: 'Email',
  //   phone: 'Téléphone',
  //   phonePlaceholder: '+33 X XX XX XX XX',
  //   message: 'Message',
  //   messagePlaceholder: 'Toute exigence spéciale ou question...',
  //   sending: 'Envoi en cours...',
  //   sendInquiry: 'Envoyer la Demande',
  //   inquirySentSuccess: 'Demande Envoyée avec Succès !',
  //   thankYouMessage: 'Merci pour votre intérêt. Nous vous recontacterons bientôt.',
  //   close: 'Fermer',
  //   previous: 'Précédent',
  //   next: 'Suivant',
  //     // Contact page translations
  //   contactHeroTitle: "Connectons-nous",
  //   contactHeroDescription: "Prêt à commencer votre voyage ? Nous sommes là pour vous aider à chaque étape. Contactez notre équipe dédiée dès aujourd'hui.",
  //   responseTime: "Nous répondons généralement dans les 2 heures",
  //   getInTouch: "Entrer en Contact",
  //   getInTouchDescription: "Nous aimerions avoir de vos nouvelles. Envoyez-nous un message et nous répondrons dès que possible.",
  //   ourOffice: "Notre Bureau",
  //   officeAddress: "Costa Rica, San Jose, Barrio Amón, Ave 13, Calle 7",
  //   phoneNumbers: "Numéros de Téléphone",
  //   phoneDetails: "+506 8701-6253 & +507 6473-6099",
  //   emailAddress: "Adresse Email",
  //   emailDetails: "info@tarasolutions-cr.com & gerencia@tarasolutions-cr.com",
  //   businessHours: "Heures d'Ouverture",
  //   businessHoursDetails: "Lun - Ven: 9:00 AM - 6:00 PM Sam: 10:00 AM - 4:00 PM",
  //   followUs: "Suivez-nous",
  //   supportAvailable: "24/7",
  //   support: "Support Disponible",
  //   avgResponseTime: "2h",
  //   responseTimeLabel: "Temps de Réponse Moyen",
  //   sendMessage: "Envoyez-nous un Message",
  //   sendMessageDescription: "Remplissez le formulaire ci-dessous et nous vous recontacterons sous peu.",
  //   personalInformation: "Informations Personnelles",
  //   fullName: "Nom complet",
  //   phoneNumber: "Numéro de téléphone",
  //   subject: "Sujet",
  //   yourMessage: "Votre Message",
  //   messagePlaceholder: "Parlez-nous de votre demande...",
  //   sendMessageButton: "Envoyer le Message",
  //   visitOurCampus: "Visitez Notre Campus",
  //   campusDescription: "Situé au cœur de la ville, notre campus est facilement accessible et équipé d'installations de pointe.",
  //     // Terms and Conditions translations
  //   termsAndConditions: "Termes et Conditions",
  //   termsDescription: "Veuillez lire ces termes attentivement avant d'utiliser nos services",
  //   lastUpdated: "Dernière Mise à Jour",
  //   dataProtection: "Protection des Données",
  //   dataProtectionDesc: "Vos informations personnelles sont sécurisées avec un chiffrement de niveau entreprise",
  //   userRights: "Droits de l'Utilisateur",
  //   userRightsDesc: "Lignes directrices claires sur vos droits et responsabilités",
  //   transparentTerms: "Termes Transparents",
  //   transparentTermsDesc: "Aucune clause cachée ou jargon juridique compliqué",
  //   termsOfService: "Conditions d'Utilisation",
  //   termsContentNotAvailable: "Le contenu des termes et conditions n'est pas disponible pour le moment.",
  //   acceptanceTitle: "Prêt à Commencer ?",
  //   acceptanceDescription: "En continuant à utiliser nos services, vous reconnaissez avoir lu et accepté nos Termes et Conditions.",
  //   acceptTerms: "J'Accepte les Termes",
  //   downloadPDF: "Télécharger Version PDF",
  //    // Privacy Policy translations
  //   privacyPolicy: "Politique de Confidentialité",
  //   privacyDescription: "Découvrez comment nous protégeons et gérons vos informations personnelles",
  //   dataSecurity: "Sécurité des Données",
  //   dataSecurityDesc: "Chiffrement de niveau entreprise et protocoles de sécurité",
  //   yourControl: "Votre Contrôle",
  //   yourControlDesc: "Contrôle total sur vos données personnelles et préférences",
  //   transparency: "Transparence",
  //   transparencyDesc: "Informations claires sur la collecte et l'utilisation des données",
  //   privacyPolicyDetails: "Détails de la Politique de Confidentialité",
  //   privacyContentNotAvailable: "Le contenu de la politique de confidentialité n'est pas disponible pour le moment.",
  //   dataCollectionOverview: "Aperçu de la Collecte de Données",
  //   whatWeCollect: "Ce que Nous Collectons",
  //   yourRights: "Vos Droits",
  //   personalInfo: "Informations personnelles et coordonnées",
  //   usageData: "Données d'utilisation et interactions avec le service",
  //   technicalData: "Données techniques et informations sur l'appareil",
  //   paymentInfo: "Informations de paiement et détails de facturation",
  //   accessData: "Accéder à vos données personnelles",
  //   correctData: "Corriger les informations inexactes",
  //   deleteData: "Supprimer vos données personnelles",
  //   objectProcessing: "S'opposer au traitement des données",
  //   privacyQuestions: "Des Questions Sur Votre Confidentialité ?",
  //   privacyContactDescription: "Notre équipe de confidentialité est là pour vous aider à comprendre vos droits et répondre à vos questions.",
  //   dataProtectionOfficer: "Délégué à la Protection des Données",
  //   downloadPrivacyPolicy: "Télécharger la Politique de Confidentialité",
  //   requestDataReport: "Demander un Rapport de Données",
  //   updatePreferences: "Mettre à Jour les Préférences",
  //    // Disclaimer & Copyright translations
  //   disclaimerCopyright: "Avertissement et Droits d'Auteur",
  //   disclaimerDescription: "Informations légales importantes sur nos services et propriété intellectuelle",
  //   importantNotice: "Avis Légal Important",
  //   disclaimerNotice: "Veuillez lire cet avertissement attentivement avant d'utiliser nos services. En accédant à notre site Web et services, vous reconnaissez et acceptez les conditions décrites ci-dessous.",
  //   liabilityDisclaimer: "Clause de Non-Responsabilité",
  //   liabilityDisclaimerDesc: "Nous ne sommes pas responsables des dommages résultant de l'utilisation de nos services",
  //   copyrightProtection: "Protection des Droits d'Auteur",
  //   copyrightProtectionDesc: "Tout le contenu est protégé par les lois internationales sur le droit d'auteur",
  //   fairUse: "Politique d'Utilisation Équitable",
  //   fairUseDesc: "Utilisation limitée autorisée à des fins éducatives et personnelles",
  //   disclaimerCopyrightDetails: "Détails de l'Avertissement et des Droits d'Auteur",
  //   legalContentNotAvailable: "Le contenu légal n'est pas disponible pour le moment.",
  //   copyrightQuickReference: "Référence Rapide des Droits d'Auteur",
  //   allowedUses: "Utilisations Autorisées",
  //   prohibitedUses: "Utilisations Interdites",
  //   personalUse: "Usage personnel et éducatif",
  //   educationalUse: "Usage en classe et formation",
  //   internalBusiness: "Référence interne d'entreprise",
  //   attributionRequired: "Avec attribution appropriée",
  //   commercialRedistribution: "Redistribution commerciale",
  //   modification: "Modification ou adaptation",
  //   removalCopyright: "Suppression des avis de droits d'auteur",
  //   reverseEngineering: "Rétro-ingénierie de logiciels",
  //   permissionsRequests: "Permissions et Demandes Légales",
  //   permissionsDescription: "Besoin d'utiliser notre contenu ou de signaler une violation ? Contactez notre équipe juridique pour les permissions et demandes légales.",
  //   mailingAddress: "Adresse Postale",
  //   downloadCopyrightPolicy: "Télécharger la Politique des Droits d'Auteur",
  //   requestPermission: "Demander une Permission",
  //   reportInfringement: "Signaler une Violation",
  //   // Copyright page translations
  //   copyrightPolicy: "Politique des Droits d'Auteur",
  //   copyrightDescription: "Protéger notre propriété intellectuelle et vos droits",
  //   copyrightPolicyDetails: "Détails de la Politique des Droits d'Auteur",
  //   copyrightContentNotAvailable: "Le contenu de la politique des droits d'auteur n'est pas disponible pour le moment.",
  //   internationalProtection: "Protection Internationale",
  //   internationalProtectionDesc: "Protégé par plusieurs traités internationaux sur le droit d'auteur",
  //   dmcaCompliant: "Conforme DMCA",
  //   dmcaCompliantDesc: "Conformité totale avec la loi sur le copyright numérique",
  //   contactInformation: "Informations de Contact",
  //   quickActions: "Actions Rapides",
  //   responseInfo: "Informations de Réponse",
  //   hours: "heures",
  //   typicalResponse: "Temps de réponse typique",
  //   emergencyResponse: "Rapports d'infraction d'urgence : 2-4 heures",
  //   legalProceedings: "Procédures légales : Action immédiate",
  //   internationalClaims: "Réclamations internationales : Réponse coordonnée",
  //    // ... existing French translations ...
  //   cookiePolicy: "Politique des Cookies",
  //   cookieDescription: "Découvrez comment nous utilisons les cookies pour améliorer votre expérience de navigation",
  //   cookiePolicyDetails: "Détails de la Politique des Cookies",
  //   cookieContentNotAvailable: "Le contenu de la politique des cookies n'est pas disponible pour le moment.",
  //   essentialCookies: "Cookies Essentiels",
  //   optionalCookies: "Cookies Optionnels",
  //   sessionManagement: "Gestion de session et sécurité",
  //   securityPurposes: "Sécurité et prévention de la fraude",
  //   siteFunctionality: "Fonctionnalités de base du site",
  //   alwaysActive: "Toujours actives (ne peuvent pas être désactivées)",
  //   analyticsTracking: "Analyse du site et suivi",
  //   marketingCookies: "Marketing et publicité",
  //   preferenceCookies: "Stockage des préférences utilisateur",
  //   thirdPartyCookies: "Cookies de services tiers",
  //   cookiePreferences: "Préférences des Cookies",
  //   necessaryCookies: "Cookies Nécessaires",
  //   necessaryCookiesDesc: "Requis pour le bon fonctionnement du site web",
  //   analyticsCookies: "Cookies d'Analyse",
  //   analyticsCookiesDesc: "Nous aident à comprendre comment les visiteurs interagissent avec notre site web",
  //   marketingCookies: "Cookies Marketing",
  //   marketingCookiesDesc: "Utilisés pour diffuser des publicités pertinentes",
  //   preferenceCookies: "Cookies de Préférences",
  //   preferenceCookiesDesc: "Mémorisent vos paramètres et préférences",
  //   savePreferences: "Enregistrer les Préférences",
  //   clearAllCookies: "Effacer Tous les Cookies",
  //   gdprCompliant: "Conforme RGPD",
  //   gdprCompliantDesc: "Entièrement conforme au Règlement Général sur la Protection des Données",
  //   transparentUsage: "Utilisation Transparente",
  //   transparentUsageDesc: "Informations claires sur tous les cookies que nous utilisons",
  //   userControl: "Contrôle Utilisateur",
  //   userControlDesc: "Contrôle total sur vos préférences de cookies",
  //   cookieQuestions: "Des Questions Sur les Cookies ?",
  //   cookieQuestionsDesc: "Notre équipe de confidentialité est là pour vous aider à comprendre notre utilisation des cookies et gérer vos préférences.",
  //   downloadCookiePolicy: "Télécharger la Politique des Cookies",
  //   updatePreferences: "Mettre à Jour les Préférences",
  //   deleteAllData: "Supprimer Toutes les Données",
  //   urgentRequests: "Demandes urgentes : 2-4 heures",
  //   dataBreachReports: "Rapports de violation de données : Action immédiate",
  //   legalInquiries: "Demandes légales : Réponse coordonnée",
  //   preferencesSaved: "Vos préférences de cookies ont été enregistrées avec succès !",
  //   confirmClearCookies: "Êtes-vous sûr de vouloir effacer tous les cookies ? Cela peut affecter votre expérience de navigation.",
  //   cookiesCleared: "Tous les cookies ont été effacés avec succès.",
    
    
  // },
};

export function LocalizationProvider({ children }) {
  const [language, setLanguage] = useState('en');

  // Initialize language from localStorage or browser preference
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else {
      // Detect browser language
      const browserLang = navigator.language.split('-')[0];
      if (translations[browserLang]) {
        setLanguage(browserLang);
      }
    }
  }, []);

  const changeLanguage = (newLanguage) => {
    if (translations[newLanguage]) {
      setLanguage(newLanguage);
      localStorage.setItem('preferred-language', newLanguage);
    }
  };

  // Translation function
  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const value = {
    language,
    setLanguage: changeLanguage,
    t,
    availableLanguages: Object.keys(translations),
  };

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  );
}

export function useLocalization() {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
}